apiVersion: apps/v1
kind: Deployment
metadata:
  name: abraxa-devops-exercise
  labels:
    app: devops-exercise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-exercise
  template:
    metadata:
      labels:
        app: devops-exercise
    spec:
      containers:
      - name: devops-exercise
        image: david94/abraxa-devops-exercise:latest
        ports:
        - containerPort: 5000
