name: ci-devops-exercise

on:
  push:
    branches:
    - develop

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run docker image from build.sh
      run: |
        cd ./container && bash build.sh david94/abraxa-devops-exercise:$GITHUB_ACTION
    - name: Login to docker and push created image.
      run: |
        docker login -p algodonD94$ -u david94
        docker push david94/abraxa-devops-exercise:$GITHUB_ACTION
      shell: bash
