name: ci-devops-exercise

on:
  push:
    branches:
    - develop

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: shellcheck
      uses: ludeeus/action-shellcheck@0.1.0
    - run: ls -la
    - run: |
        cd ./container
        ls -la
    - name: Run docker image from build.sh
      run: |
        gedit build.sh
        sh build.sh $GITHUB_REPOSITORY:$GITHUB_ACTION
    - name: Login to docker and push created image.
      run: |
        docker login -p ${{ secrets.DOCKER_USER }} -u ${{ secrets.DOCKER_PASS }}
        docker push $GITHUB_REPOSITORY:$GITHUB_ACTION
      shell: bash
