---

name: ci-devops-exercise

on:
  push:
    branches:
      - develop

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: python-lint
        uses: CyberZHG/github-action-python-lint@0.0.2
      - name: Run docker image from build.sh
        run: |
          cd ./container && bash build.sh ${{secrets.DOCKER_USER}}/abraxa-devops-exercise:latest
          docker login -p ${{secrets.DOCKER_PASS}} -u ${{secrets.DOCKER_USER}}
          docker push ${{secrets.DOCKER_USER}}/abraxa-devops-exercise:latest
        shell: bash
